# Application Secrets

# Store secrets in the .env* files as provided by the [dotenv](https://github.com/bkeepers/dotenv) gem.
# Be sure to restart your server when you modify this file.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

stage:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
