source "https://rubygems.org"

gem "rake"
gem "naught"
gem "fast_blank"
gem "bcrypt-ruby"
gem "sqlite3"
gem "rack-attack"
gem "rails", "4.0.0"
gem "will_paginate"
gem "bootstrap-will_paginate"
gem "cancan"
gem "resourcer"
gem "sessioner"
gem "squeel"
gem "ransack"
gem "state_machine"
gem "redis"
gem "redis-namespace"
gem "linguist"
gem "simple_form"
gem "tokener"
gem "sorter"
gem "lineage"
gem "RedCloth"
gem "aws-sdk"
gem "paperclip_plus"
gem "prawn_plus"
gem "browser_details"
gem "breach-mitigation-rails"

gem "sass-rails"
gem "coffee-rails"
gem "uglifier"
gem "bootstrap-sass"
gem "bourbon"

group :doc do
  # Run "rake doc:rails" to generate API in the doc/api folder.
  gem "sdoc", :require => false
end

group :development, :test do
  gem "pry"
  gem "pry-byebug"
  gem "pry-remote"
  gem "pry-rescue"
  gem "pry-stack_explorer"
  gem "pry-vterm_aliases"
  gem "pry-doc"
  gem "log_plus"
  gem "launchy" # Allows save_and_open_page to work in Capybara.
end

group :development do
  gem "bond"
  gem "wirb"
  gem "hirb"
  gem "awesome_print"
  gem "capistrano"
  gem "active_sanity"
  gem "quiet_assets"
  gem "mailcatcher"
  gem "rails-erd"
  gem "railroady"
  gem "license_finder"
  gem "xray-rails"
  gem "better_errors"
  gem "meta_request" # Required by the RailsPanel browser extension.
  gem "rb-fsevent" # Guard file events for OSX.
  gem "guard-rspec"
  gem "rack-livereload"
  gem "guard-livereload"
  gem "chrome_logger"
  gem "bullet"
  gem "rack-mini-profiler"
  gem "flay"
end

group :test do
  gem "rspec-rails"
  gem "factory_girl_rails"
  gem "capybara"
  gem "database_cleaner"
  gem "fakeweb"
  gem "vcr"
  gem "timecop"
end
