source "https://rubygems.org"

# Databases
gem "sqlite3"
gem "redis"
gem "redis-namespace"

# Cache
gem "dalli"

# Server
gem "unicorn"

# Application
gem "rake"
gem "rails", "~> 4.1"
gem "naught"
gem "tokener"
gem "sessioner"
gem "resourcer"
gem "ransack"
gem "state_machine"
gem "linguist"
gem "sorter"
gem "lineage"
gem "navigator"
gem "will_paginate"
gem "prawn_plus"
gem "aws-sdk"
gem "paperclip_plus"
gem "number_to_fraction"
gem "gravatarify"

# Assets
gem "uglifier"
gem "slim-rails"
gem "sass-rails", "~> 4.0.3"
gem "bower-rails"
gem "jquery-rails"
gem "modernizr-rails"
gem "foundation-rails"

# API
gem "jbuilder"

# Performance
gem "fast_blank"
gem "deep_tree"

# Security
gem "bcrypt"
gem "rack-attack"
gem "secure_headers"
gem "auther"

# Metrics
gem "browser_details"

group :production do
  gem "rails_12factor"
end

group :development, :test do
  gem "dotenv-rails"
  gem "pry"
  gem "pry-byebug"
  gem "pry-remote"
  gem "pry-rescue"
  gem "pry-stack_explorer"
  gem "bond"
  gem "wirb"
  gem "hirb"
  gem "awesome_print"
  gem "priscilla"
  gem "active_sanity"
  gem "quiet_assets"
  gem "rails_db_info"
  gem "log_plus"
end

group :development do
  gem "better_errors"
  # gem "sprockets_better_errors" # Disabled due to lack of Rails 4.1.x support.
  gem "web-console"
  gem "xray-rails"
  gem "meta_request" # Required by the RailsPanel browser extension.
  gem "rb-fsevent" # Guard file events for OSX.
  gem "guard-bundler"
  gem "guard-rspec"
  gem "rack-livereload"
  gem "guard-livereload"
  gem "bullet"
  gem "tracer_bullets"
  gem "rack-mini-profiler"
  gem "rails-footnotes"
  gem "rails-erd"
  gem "railroady"
  gem "spring"
  gem "spring-commands-rspec"
end

group :test do
  gem "database_cleaner"
  gem "factory_girl_rails"
  gem "rspec-rails"
  gem "timecop"
  gem "typhoeus"
  gem "vcr"
  gem "launchy" # Allows save_and_open_page to work in Capybara.
  gem "capybara"
  gem "capybara-extensions"
  gem "simplecov"
end
