source "https://rubygems.org"

# Databases
gem "sqlite3"
gem "redis"
gem "redis-namespace"

# Cache
gem "dalli"

# Server
gem "puma"

# Application
gem "rake"
gem "rails", "4.0.4"
gem "naught"
gem "tokener"
gem "sessioner"
gem "resourcer"
gem "cancan"
gem "squeel"
gem "ransack"
gem "simple_form"
gem "state_machine"
gem "linguist"
gem "sorter"
gem "lineage"
gem "navigator"
gem "will_paginate"
gem "RedCloth"
gem "prawn_plus"
gem "aws-sdk"
gem "paperclip_plus"
gem "number_to_fraction"
gem "gravatarify"

# Assets
gem "uglifier"
gem "slim-rails"
gem "sass-rails"
gem "jquery-rails"
gem "modernizr-rails"
gem "foundation-rails"
gem "bourbon"

# Performance
gem "fast_blank"
gem "deep_tree"

# Security
gem "bcrypt"
gem "rack-attack"
gem "secure_headers"
gem "breach-mitigation-rails"

# Metrics
gem "browser_details"

group :development, :test do
  gem "dotenv-rails"
  gem "pry"
  gem "pry-byebug"
  gem "pry-remote"
  gem "pry-rescue"
  gem "pry-stack_explorer"
  gem "bond"
  gem "wirb"
  gem "hirb"
  gem "awesome_print"
  gem "active_sanity"
  gem "quiet_assets"
  gem "rails_db_info"
  gem "log_plus"
end

group :development do
  gem "capistrano"
  gem "better_errors"
  gem "sprockets_better_errors"
  gem "web-console"
  gem "xray-rails"
  gem "meta_request" # Required by the RailsPanel browser extension.
  gem "rb-fsevent" # Guard file events for OSX.
  gem "guard-rspec"
  gem "rack-livereload"
  gem "guard-livereload"
  gem "bullet"
  gem "tracer_bullets"
  gem "rack-mini-profiler"
  gem "rails-footnotes"
  gem "rails-erd"
  gem "railroady"
  gem "spring"
end

group :test do
  gem "database_cleaner"
  gem "factory_girl_rails"
  gem "rspec-rails"
  gem "timecop"
  gem "webmock"
  gem "vcr"
  gem "launchy" # Allows save_and_open_page to work in Capybara.
  gem "capybara"
  gem "capybara-extensions"
  gem "simplecov"
end
